package com.shopapotheke.githubrepositorylist.models;


public enum ProgramingLanguages {
    C_SHARP("C#"),
    CSS("CSS"),
    COFFEE_SCRIPT("CoffeeScript"),
    DART("Dart"),
    DM("DM"),
    C_PLUS_PLUS("C++"),
    ELIXIR("Elixir"),
    GO("Go"),
    GROOVY("Groovy"),
    HTML("HTML"),
    JAVA("Java"),
    JAVASCRIPT("JavaScript"),
    KOTLIN("Kotlin"),
    OBJECT_C("Objective-C"),
    PERL("Perl"),
    PHP("PHP"),
    POWERSHELL("PowerShell"),
    PYTHON("Python"),
    RUBY("Ruby"),
    RUST("Rust"),
    SCALA("Scala"),
    SHELL("Shell"),
    SWIFT("Swift"),
    TYPESCRIPT("TypeScript"),
    FOUR_D("4D"),
    ABAP("ABAP"),
    ABNF("ABNF"),
    ActionScript("ActionScript"),
    Ada("Ada"),
    Adobe_Font_Metrics("Adobe Font Metrics"),
    Agda("Agda"),
    AGS_Script("AGS Script"),
    AL("AL"),
    Alloy("Alloy"),
    Alpine_Abuild("Alpine Abuild"),
    Altium_Designer("Altium Designer"),
    AMPL("AMPL"),
    AngelScript("AngelScript"),
    Ant_Build_System("Ant Build System"),
    ANTLR("ANTLR"),
    ApacheConf("ApacheConf"),
    Apex("Apex"),
    API_Blueprint("API Blueprint"),
    APL("APL"),
    Apollo_Guidance_Computer("Apollo Guidance Computer"),
    AppleScript("AppleScript"),
    Arc("Arc"),
    AsciiDoc("AsciiDoc"),
    ASL("ASL"),
    ASN_ONE("ASN.1"),
    ASP_DOT_NET("ASP.NET"),
    AspectJ("AspectJ"),
    Assembly("Assembly"),
    Asymptote("Asymptote"),
    ATS("ATS"),
    Augeas("Augeas"),
    AutoHotkey("AutoHotkey"),
    AutoIt("AutoIt"),
    Avro_IDL("Avro IDL"),
    Awk("Awk"),
    Ballerina("Ballerina"),
    Batchfile("Batchfile"),
    Befunge("Befunge"),
    BibTeX("BibTeX"),
    Bison("Bison"),
    BitBake("BitBake"),
    Blade("Blade"),
    BlitzBasic("BlitzBasic"),
    BlitzMax("BlitzMax"),
    Bluespec("Bluespec"),
    Boo("Boo"),
    Brainfuck("Brainfuck"),
    Brightscript("Brightscript"),
    C_OBJ_DUMP("C-ObjDump"),
    C2hs_Haskell("C2hs Haskell"),
    Cabal_Config("Cabal Config"),
    CAP_N_PORTO("Cap'n_Proto"),
    CartoCSS("CartoCSS"),
    Ceylon("Ceylon"),
    Chapel("Chapel"),
    Charity("Charity"),
    ChucK("ChucK"),
    Cirru("Cirru"),
    Clarion("Clarion"),
    Classic_ASP("Classic ASP"),
    Clean("Clean"),
    Click("Click"),
    CLIPS("CLIPS"),
    Clojure("Clojure"),
    Closure_Templates("Closure Templates"),
    Cloud_Firestore_Security_Rules("Cloud Firestore Security Rules"),
    CMake("CMake"),
    COBOL("COBOL"),
    CodeQL("CodeQL"),
    ColdFusion("ColdFusion"),
    ColdFusion_CFC("ColdFusion CFC"),
    COLLADA("COLLADA"),
    Common_Lisp("Common Lisp"),
    Common_Workflow_Language("Common Workflow Language"),
    Component_Pascal("Component Pascal"),
    CONLL_U("CoNLL-U"),
    Cool("Cool"),
    Coq("Coq"),
    CPP_OBJDUMP("Cpp-ObjDump"),
    Creole("Creole"),
    Crystal("Crystal"),
    CSON("CSON"),
    Csound("Csound"),
    Csound_Document("Csound Document"),
    Csound_Score("Csound Score"),
    CSV("CSV"),
    Cuda("Cuda"),
    cURL_Config("cURL Config"),
    CWeb("CWeb"),
    Cycript("Cycript"),
    Cython("Cython"),
    D("D"),
    D_OBJDUMP("D-ObjDump"),
    Dafny("Dafny"),
    Darcs_Patch("Darcs Patch"),
    DataWeave("DataWeave"),
    desktop("desktop"),
    Dhall("Dhall"),
    Diff("Diff"),
    DIGITAL_Command_Language("DIGITAL Command Language"),
    dircolors("dircolors"),
    DirectX_3D_File("DirectX 3D File"),
    DNS_Zone("DNS Zone"),
    Dockerfile("Dockerfile"),
    Dogescript("Dogescript"),
    DTrace("DTrace"),
    Dylan("Dylan"),
    E("E"),
    Eagle("Eagle"),
    Easybuild("Easybuild"),
    EBNF("EBNF"),
    eC("eC"),
    Ecere_Projects("Ecere Projects"),
    ECL("ECL"),
    ECLiPSe("ECLiPSe"),
    EditorConfig("EditorConfig"),
    Edje_Data_Collection("Edje Data Collection"),
    edn("edn"),
    Eiffel("Eiffel"),
    EJS("EJS"),
    Elm("Elm"),
    Emacs_Lisp("Emacs Lisp"),
    EmberScript("EmberScript"),
    EML("EML"),
    EQ("EQ"),
    Erlang("Erlang"),
    F_SHARP("F#"),
    F_STAT("F*"),
    Factor("Factor"),
    Fancy("Fancy"),
    Fantom("Fantom"),
    Faust("Faust"),
    FIGlet_Font("FIGlet Font"),
    Filebench_WML("Filebench WML"),
    Filterscript("Filterscript"),
    fish("fish"),
    FLUX("FLUX"),
    Formatted("Formatted"),
    Forth("Forth"),
    Fortran("Fortran"),
    Fortran_Free_Form("Fortran Free Form"),
    FreeMarker("FreeMarker"),
    Frege("Frege"),
    Futhark("Futhark"),
    G_CODE("G-code"),
    Game_Maker_Language("Game Maker Language"),
    GAML("GAML"),
    GAMS("GAMS"),
    GAP("GAP"),
    GCC_Machine_Description("GCC Machine Description"),
    GDB("GDB"),
    GDScript("GDScript"),
    GEDCOM("GEDCOM"),
    Genie("Genie"),
    Genshi("Genshi"),
    Gentoo_Ebuild("Gentoo Ebuild"),
    Gentoo_Eclass("Gentoo Eclass"),
    Gerber_Image("Gerber Image"),
    Gettext_Catalog("Gettext Catalog"),
    Gherkin("Gherkin"),
    Git_Attributes("Git Attributes"),
    Git_Config("Git Config"),
    GLSL("GLSL"),
    Glyph("Glyph"),
    Glyph_Bitmap_Distribution_Format("Glyph Bitmap Distribution Format"),
    GN("GN"),
    Gnuplot("Gnuplot"),
    Golo("Golo"),
    Gosu("Gosu"),
    Grace("Grace"),
    Gradle("Gradle"),
    Grammatical_Framework("Grammatical Framework"),
    Graph_Modeling_Language("Graph Modeling Language"),
    GraphQL("GraphQL"),
    Graphviz_DOT("Graphviz_(DOT)"),
    Groovy_Server_Pages("Groovy Server Pages"),
    Hack("Hack"),
    Haml("Haml"),
    Handlebars("Handlebars"),
    HAProxy("HAProxy"),
    Harbour("Harbour"),
    Haskell("Haskell"),
    Haxe("Haxe"),
    HCL("HCL"),
    HiveQL("HiveQL"),
    HLSL("HLSL"),
    HolyC("HolyC"),
    HTML_AND_Django("HTML+Django"),
    HTML_AND_ECR("HTML+ECR"),
    HTML_AND_EEX("HTML+EEX"),
    HTML_AND_ERB("HTML+ERB"),
    HTML_AND_PHP("HTML+PHP"),
    HTML_AND_Razor("HTML+Razor"),
    HTTP("HTTP"),
    HXML("HXML"),
    Hy("Hy"),
    HyPhy("HyPhy"),
    IDL("IDL"),
    Idris("Idris"),
    Ignore_List("Ignore List"),
    IGOR_Pro("IGOR Pro"),
    Inform_7("Inform 7"),
    INI("INI"),
    Inno_Setup("Inno Setup"),
    Io("Io"),
    Ioke("Ioke"),
    IRC_log("IRC log"),
    Isabelle("Isabelle"),
    Isabelle_ROOT("Isabelle ROOT"),
    J("J"),
    Jasmin("Jasmin"),
    Java_Properties("Java Properties"),
    Java_Server_Pages("Java Server Pages"),
    JAVASCRIPT_AND_ERB("JavaScript+ERB"),
    JFlex("JFlex"),
    Jison("Jison"),
    Jison_Lex("Jison Lex"),
    Jolie("Jolie"),
    JSON("JSON"),
    JSON_with_Comments("JSON with Comments"),
    JSON5("JSON5"),
    JSONiq("JSONiq"),
    JSONLD("JSONLD"),
    Jsonnet("Jsonnet"),
    JSX("JSX"),
    Julia("Julia"),
    Jupyter_Notebook("Jupyter Notebook"),
    Kaitai_Struct("Kaitai Struct"),
    KiCad_Layout("KiCad Layout"),
    KiCad_Legacy_Layout("KiCad Legacy Layout"),
    KiCad_Schematic("KiCad Schematic"),
    Kit("Kit"),
    KRL("KRL"),
    LabVIEW("LabVIEW"),
    Lasso("Lasso"),
    Latte("Latte"),
    Lean("Lean"),
    Less("Less"),
    Lex("Lex"),
    LFE("LFE"),
    LilyPond("LilyPond"),
    Limbo("Limbo"),
    Linker_Script("Linker Script"),
    Linux_Kernel_Module("Linux Kernel Module"),
    Liquid("Liquid"),
    Literate_Agda("Literate Agda"),
    Literate_CoffeeScript("Literate CoffeeScript"),
    Literate_Haskell("Literate Haskell"),
    LiveScript("LiveScript"),
    LLVM("LLVM"),
    Logos("Logos"),
    Logtalk("Logtalk"),
    LOLCODE("LOLCODE"),
    LookML("LookML"),
    LoomScript("LoomScript"),
    LSL("LSL"),
    LTspice_Symbol("LTspice Symbol"),
    Lua("Lua"),
    M("M"),
    M4("M4"),
    M4Sugar("M4Sugar"),
    Macaulay2("Macaulay2"),
    Makefile("Makefile"),
    Mako("Mako"),
    Markdown("Markdown"),
    Marko("Marko"),
    Mask("Mask"),
    Mathematica("Mathematica"),
    MATLAB("MATLAB"),
    Maven_POM("Maven POM"),
    Max("Max"),
    MAXScript("MAXScript"),
    mcfunction("mcfunction"),
    MediaWiki("MediaWiki"),
    Mercury("Mercury"),
    Meson("Meson"),
    Metal("Metal"),
    Microsoft_Developer_Studio_Project("Microsoft Developer Studio Project"),
    MiniD("MiniD"),
    Mirah("Mirah"),
    mIRC_Script("mIRC Script"),
    MLIR("MLIR"),
    Modelica("Modelica"),
    MODULA_2("Modula-2"),
    MODULA_3("Modula-3"),
    Module_Management_System("Module Management System"),
    Monkey("Monkey"),
    Moocode("Moocode"),
    MoonScript("MoonScript"),
    Motorola_68K_Assembly("Motorola 68K Assembly"),
    MQL4("MQL4"),
    MQL5("MQL5"),
    MTML("MTML"),
    MUF("MUF"),
    mupad("mupad"),
    Muse("Muse"),
    Mustache("Mustache"),
    Myghty("Myghty"),
    nanorc("nanorc"),
    NASL("NASL"),
    NCL("NCL"),
    Nearley("Nearley"),
    Nemerle("Nemerle"),
    NEON("NEON"),
    nesC("nesC"),
    NetLinx("NetLinx"),
    NETLINX_AND_ERB("NetLinx+ERB"),
    NetLogo("NetLogo"),
    NewLisp("NewLisp"),
    Nextflow("Nextflow"),
    Nginx("Nginx"),
    Nim("Nim"),
    Ninja("Ninja"),
    Nit("Nit"),
    Nix("Nix"),
    NL("NL"),
    NPM_Config("NPM Config"),
    NSIS("NSIS"),
    Nu("Nu"),
    NumPy("NumPy"),
    ObjDump("ObjDump"),
    Object_Data_Instance_Notation("Object Data Instance Notation"),
    OBJECTIVE_C_PLUS_PLUS("Objective-C++"),
    OBJECTIVE_J("Objective-J"),
    ObjectScript("ObjectScript"),
    OCaml("OCaml"),
    Odin("Odin"),
    Omgrofl("Omgrofl"),
    ooc("ooc"),
    Opa("Opa"),
    Opal("Opal"),
    Open_Policy_Agent("Open Policy Agent"),
    OpenCL("OpenCL"),
    OpenEdge_ABL("OpenEdge ABL"),
    OpenQASM("OpenQASM"),
    OpenRC_runscript("OpenRC runscript"),
    OpenSCAD("OpenSCAD"),
    OpenStep_Property_List("OpenStep Property List"),
    OpenType_Feature_File("OpenType Feature File"),
    Org("Org"),
    Ox("Ox"),
    Oxygene("Oxygene"),
    Oz("Oz"),
    P4("P4"),
    Pan("Pan"),
    Papyrus("Papyrus"),
    Parrot("Parrot"),
    Parrot_Assembly("Parrot Assembly"),
    Parrot_Internal_Representation("Parrot Internal Representation"),
    Pascal("Pascal"),
    Pawn("Pawn"),
    Pep8("Pep8"),
    Pic("Pic"),
    Pickle("Pickle"),
    PicoLisp("PicoLisp"),
    PigLatin("PigLatin"),
    Pike("Pike"),
    PlantUML("PlantUML"),
    PLpgSQL("PLpgSQL"),
    PLSQL("PLSQL"),
    Pod("Pod"),
    Pod_6("Pod 6"),
    PogoScript("PogoScript"),
    Pony("Pony"),
    PostCSS("PostCSS"),
    PostScript("PostScript"),
    POV_RAY_SDL("POV-Ray_SDL"),
    PowerBuilder("PowerBuilder"),
    Prisma("Prisma"),
    Processing("Processing"),
    Proguard("Proguard"),
    Prolog("Prolog"),
    Propeller_Spin("Propeller Spin"),
    Protocol_Buffer("Protocol Buffer"),
    Public_Key("Public Key"),
    Pug("Pug"),
    Puppet("Puppet"),
    Pure_Data("Pure Data"),
    PureBasic("PureBasic"),
    PureScript("PureScript"),
    Python_console("Python console"),
    Python_traceback("Python traceback"),
    q("q"),
    Q_SHARP("Q#"),
    QMake("QMake"),
    QML("QML"),
    Qt_Script("Qt Script"),
    Quake("Quake"),
    R("R"),
    Racket("Racket"),
    Ragel("Ragel"),
    Raku("Raku"),
    RAML("RAML"),
    Rascal("Rascal"),
    Raw_token_data("Raw token data"),
    RDoc("RDoc"),
    Readline_Config("Readline Config"),
    REALbasic("REALbasic"),
    Reason("Reason"),
    Rebol("Rebol"),
    Red("Red"),
    Redcode("Redcode"),
    Regular_Expression("Regular Expression"),
    REN_PY("Ren'Py"),
    RenderScript("RenderScript"),
    reStructuredText("reStructuredText"),
    REXX("REXX"),
    Rich_Text_Format("Rich Text Format"),
    Ring("Ring"),
    Riot("Riot"),
    RMarkdown("RMarkdown"),
    RobotFramework("RobotFramework"),
    Roff("Roff"),
    Roff_Manpage("Roff Manpage"),
    Rouge("Rouge"),
    RPC("RPC"),
    RPM_Spec("RPM Spec"),
    RUNOFF("RUNOFF"),
    Sage("Sage"),
    SaltStack("SaltStack"),
    SAS("SAS"),
    Sass("Sass"),
    Scaml("Scaml"),
    Scheme("Scheme"),
    Scilab("Scilab"),
    SCSS("SCSS"),
    sed("sed"),
    Self("Self"),
    ShaderLab("ShaderLab"),
    ShellSession("ShellSession"),
    Shen("Shen"),
    Sieve("Sieve"),
    Slash("Slash"),
    Slice("Slice"),
    Slim("Slim"),
    Smali("Smali"),
    Smalltalk("Smalltalk"),
    Smarty("Smarty"),
    SmPL("SmPL"),
    SMT("SMT"),
    Solidity("Solidity"),
    SourcePawn("SourcePawn"),
    SPARQL("SPARQL"),
    Spline_Font_Database("Spline Font Database"),
    SQF("SQF"),
    SQL("SQL"),
    SQLPL("SQLPL"),
    Squirrel("Squirrel"),
    SRecode_Template("SRecode Template"),
    SSH_Config("SSH Config"),
    Stan("Stan"),
    Standard_ML("Standard ML"),
    Starlark("Starlark"),
    Stata("Stata"),
    STON("STON"),
    Stylus("Stylus"),
    SubRip_Text("SubRip Text"),
    SugarSS("SugarSS"),
    SuperCollider("SuperCollider"),
    Svelte("Svelte"),
    SVG("SVG"),
    SWIG("SWIG"),
    SystemVerilog("SystemVerilog"),
    Tcl("Tcl"),
    Tcsh("Tcsh"),
    Tea("Tea"),
    Terra("Terra"),
    TeX("TeX"),
    Texinfo("Texinfo"),
    Text("Text"),
    Textile("Textile"),
    Thrift("Thrift"),
    TI_Program("TI Program"),
    TLA("TLA"),
    TOML("TOML"),
    TSQL("TSQL"),
    TSV("TSV"),
    TSX("TSX"),
    Turing("Turing"),
    Turtle("Turtle"),
    Twig("Twig"),
    TXL("TXL"),
    Type_Language("Type Language"),
    Unified_Parallel_C("Unified Parallel C"),
    Unity3D_Asset("Unity3D Asset"),
    Unix_Assembly("Unix Assembly"),
    Uno("Uno"),
    UnrealScript("UnrealScript"),
    UrWeb("UrWeb"),
    V("V"),
    Vala("Vala"),
    VBA("VBA"),
    VBScript("VBScript"),
    VCL("VCL"),
    Verilog("Verilog"),
    VHDL("VHDL"),
    Vim_Help_File("Vim Help File"),
    Vim_script("Vim script"),
    Vim_Snippet("Vim Snippet"),
    VISUAL_BASIC_DOT_NET("Visual_Basic_.NET"),
    Volt("Volt"),
    Vue("Vue"),
    Wavefront_Material("Wavefront Material"),
    Wavefront_Object("Wavefront Object"),
    wdl("wdl"),
    Web_Ontology_Language("Web Ontology Language"),
    WebAssembly("WebAssembly"),
    WebIDL("WebIDL"),
    WebVTT("WebVTT"),
    Wget_Config("Wget Config"),
    Windows_Registry_Entries("Windows Registry Entries"),
    wisp("wisp"),
    Wollok("Wollok"),
    World_of_Warcraft_Addon_Data("World of Warcraft Addon Data"),
    X_BitMap("X BitMap"),
    X_Font_Directory_Index("X Font Directory Index"),
    X_PixMap("X PixMap"),
    X10("X10"),
    xBase("xBase"),
    XC("XC"),
    XCompose("XCompose"),
    XML("XML"),
    XML_Property_List("XML Property List"),
    Xojo("Xojo"),
    XPages("XPages"),
    XProc("XProc"),
    XQuery("XQuery"),
    XS("XS"),
    XSLT("XSLT"),
    Xtend("Xtend"),
    Yacc("Yacc"),
    YAML("YAML"),
    YANG("YANG"),
    YARA("YARA"),
    YASnippet("YASnippet"),
    ZAP("ZAP"),
    Zeek("Zeek"),
    ZenScript("ZenScript"),
    Zephir("Zephir"),
    Zig("Zig"),
    ZIL("ZIL"),
    Zimpl("Zimpl");

    private final String programingLanguage;


    ProgramingLanguages(String programingLanguage) {
        this.programingLanguage = programingLanguage;
    }

    public String getProgramingLanguage() {
        return programingLanguage;
    }
}
